/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.python.util;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int shell=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int cancel_cn=0x7f040003;
        public static final int cancel_en=0x7f040004;
        public static final int setting=0x7f040006;
        public static final int sure_cn=0x7f040001;
        public static final int sure_en=0x7f040002;
        public static final int welcome=0x7f040005;
    }
}
